package com.sendsafely.enums;

public enum APIResponse {
	SUCCESS,
	FAIL,
	OUTDATED_VERSION,
	LIMIT_EXCEEDED,
	GUESTS_PROHIBITED,
	DENIED,
	INVALID_EMAIL,
	DUPLICATE_EMAIL,
	APPROVER_REQUIRED,
	AUTHENTICATION_FAILED,
	UNKNOWN_PACKAGE,
	INVALID_INPUT,
	INVALID_RECIPIENT,
	PACKAGE_NEEDS_APPROVAL,
	PASSWORD_REQUIRED
}
