package com.sendsafely.enums;

public enum Endpoint {

	USER_INFORMATION, 
	VerifyVersion, 
	VerifyCredentials, 
	ENTERPRISE_INFO, 
	CREATE_PACKAGE, 
	CREATE_DIRECTORY,
	ADD_RECIPIENT,
	UPDATE_RECIPIENT, 
	DELETE_PACKAGE, 
	PACKAGE_INFORMATION, 
	PACKAGE_LIFE, 
	ACTIVE_PACKAGES, 
	ARCHIVED_PACKAGES, 
	ADD_FILE, 
	UPLOAD_FILE, 
	ADD_MESSAGE, 
	FINALIZE_PACKAGE, 
	ADD_PHONENUMBER,
	FILE_HISTORY,
	ORGANIZATION_PACKAGES,
	GET_DIRECTORY, 
	PACKAGE_NAME, 
	MOVE_FILE,
	MOVE_DIRECTORY,
	FILE_INFORMATION,
	DELETE_FILE, 
	DIRECTORY_NAME, 
	DELETE_DIRECTORY, 
	GET_ACTIVITY_LOG
	
}
