package com.sendsafely.enums;

public enum GetParam {

	PACKAGE_ID, PACKAGE_CODE, FILE_ID, DIRECTORY_ID, API, VERSION_NO, USER_ID, CHECKSUM, PUBLIC_KEY_ID, GROUP_ID, RECIPIENT_ID, RECIPIENT_EMAIL, SOURCE_DIRECTORY_ID, TARGET_DIRECTORY_ID;
	
}
