package com.sendsafely.enums;

/**
 * Enum describing the current state of the package.
 * @author Erik Larsson
 *
 */
public enum PackageState {

	PACKAGE_STATE_DELETED_PARTIALLY_COMPLETE, 
	PACKAGE_STATE_DELETED_INCOMPLETE, 
	PACKAGE_STATE_TEMP, 
	PACKAGE_STATE_DELETED_COMPLETE, 
	PACKAGE_STATE_IN_PROGRESS, 
	PACKAGE_STATE_EXPIRED_INCOMPLETE,
	PACKAGE_STATE_EXPIRED_COMPLETE,
	PACKAGE_STATE_ACTIVE_COMPLETE,
	PACKAGE_STATE_ACTIVE_INCOMPLETE,
	PACKAGE_STATE_ACTIVE_PARTIALLY_COMPLETE,
	PACKAGE_STATE_EXPIRED_PARTIALLY_COMPLETE;
	
}
