package com.sendsafely.enums;

public enum Endpoint {

	USER_INFORMATION, VerifyVersion, VerifyCredentials, ENTERPRISE_INFO, CREATE_PACKAGE, ADD_RECIPIENT, UPDATE_RECIPIENT, DELETE_PACKAGE, PACKAGE_INFORMATION, PACKAGE_LIFE, ACTIVE_PACKAGES, ARCHIVED_PACKAGES, ADD_FILE, UPLOAD_FILE, ADD_MESSAGE, FINALIZE_PACKAGE, ADD_PHONENUMBER;
	
}
